--
--  ALTERING TProduct and TRating to have temporal tables
--

-- Table creation with history
ALTER TABLE TProduct
ADD dStart DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETUTCDATE(),
	dEnd DATETIME2 GENERATED ALWAYS AS ROW END DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
PERIOD FOR SYSTEM_TIME (dStart, dEnd);

ALTER TABLE TProduct SET (SYSTEM_VERSIONING = ON);

ALTER TABLE TRating
ADD dStart DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETUTCDATE(),
	dEnd DATETIME2 GENERATED ALWAYS AS ROW END DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
PERIOD FOR SYSTEM_TIME (dStart, dEnd);

ALTER TABLE TRating SET (SYSTEM_VERSIONING = ON);