CREATE TABLE TProduct (
	nProductID INT PRIMARY KEY IDENTITY,
	cName VARCHAR(200) NOT NULL,
	cDescription TEXT NOT NULL,
	nPrice INT NOT NULL,
	nCurrentStock INT NOT NULL,
    nAverageRating FLOAT(4) NOT NULL DEFAULT 0
);

CREATE TABLE TCity (
	nCityID INT PRIMARY KEY IDENTITY,
    cCity VARCHAR(50) NOT NULL 
);

CREATE TABLE TUsers (
	nUserID INT PRIMARY KEY IDENTITY,
	cFirstName VARCHAR(64) NOT NULL,
	cLastName VARCHAR(64) NOT NULL,
	cAddress VARCHAR(255) NOT NULL,
	cZipCode CHAR(4) NOT NULL,
	cPhoneNumber VARCHAR(16) NOT NULL UNIQUE,
	cEmail VARCHAR(255) NOT NULL UNIQUE,
	cPassword VARCHAR(255) NOT NULL,
    nTotalAmount INT NOT NULL,
	nCityID INT FOREIGN KEY REFERENCES TCity(nCityID)
);

CREATE TABLE TCard (
	nCardID INT PRIMARY KEY IDENTITY,
    cCardNumber VARCHAR(22) NOT NULL UNIQUE,
	cCardHolder VARCHAR(255) NOT NULL,
	dExpireDate DATE NOT NULL,
	cCCV CHAR(3),
    nTotalAmount INT NOT NULL,
	nUserID INT FOREIGN KEY REFERENCES TUsers(nUserID)
);

CREATE TABLE TInvoice (
	nInvoiceID INT PRIMARY KEY IDENTITY,
	dIssueDate DATETIME NOT NULL,
	nTax INT NOT NULL,
	nTotalAmount INT NOT NULL,
	nCardID INT FOREIGN KEY REFERENCES TCard(nCardID)

);

CREATE TABLE TInvoiceLine (
	nProduct_invoiceID INT PRIMARY KEY IDENTITY,
	nProductID INT FOREIGN KEY REFERENCES TProduct(nProductID),
	nInvoiceID INT FOREIGN KEY REFERENCES TInvoice(nInvoiceID),
	nQuantity INT NOT NULL,
	nPrice INT NOT NULL
);

CREATE TABLE TRating (
    nRatingID INT PRIMARY KEY IDENTITY,
	nUserID INT FOREIGN KEY REFERENCES TUsers(nUserID),
	nProductID INT FOREIGN KEY REFERENCES TProduct(nProductID),
	nRating float(4) CHECK (nRating BETWEEN 0 AND 5),
    cComment TEXT 
);
